title: "Md Rayhanul Masud"
description: "PhD Candidate, Software Engineering & Cybersecurity — UC Riverside"
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://mrayhanulmasud.github.io"  # change if your username is different
theme: minima
# Enable kramdown + syntax highlighting
markdown: kramdown
highlighter: rouge

# Navigation — order matters
header_pages:
  - index.md
  - publications.md
  - news.md
  - blog.md
  - projects.md
  - contact.md

# Social links (used by minima)
author:
  name: "Md Rayhanul Masud"
  email: "mmasu012@ucr.edu"
  linkedin: "md-rayhanul-masud"
  scholar: "https://scholar.google.com/citations?user=nY889B0AAAAJ"
  github: "mrayhanulmasud"
  twitter: ""

# Footer
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/mrayhanulmasud" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/md-rayhanul-masud" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=nY889B0AAAAJ" }

# Collections (optional future use)
collections:
  pages:
    output: true

# Build
plugins:
  - jekyll-feed
  - jekyll-seo-tag